<a href="https://colab.research.google.com/github/saisampaththumati-datascientists/NLP-natural_learning_language-/blob/main/pyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.3.0+cu121'

In [ ]:
!nvidia-smi


Wed Jul 10 17:50:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      Off | 00000000:00:03.0 Off |                    0 |
| N/A   36C    P8              12W /  72W |      1MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensor
- Create the scaler
- PyTorch tensors. are created using torch.Tensor()https://pytorch.org/docs/stable/tensors.html

In [ ]:
scaler=torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# it return the number from the tensor
scaler.item()

7

In [ ]:
# what is the vector ? magintude and the direction
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
Matrix= torch.tensor([[2,3],[3,4]])
Matrix

tensor([[2, 3],
        [3, 4]])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[1][0]

tensor(3)

In [ ]:
Tensor=torch.tensor([[[3,4,5],[1,5,6],[7,8,9]]])
Tensor

tensor([[[3, 4, 5],
         [1, 5, 6],
         [7, 8, 9]]])

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor[0][2]

tensor([7, 8, 9])

# Random Tensor
- Why Random Tensor ?
Random tensor are important because the way many neural network learn is that start with tensor full of random numbers

In [ ]:
Random = torch.rand(3,4,2)
# random element are generated
Random

tensor([[[0.0343, 0.3756],
         [0.2939, 0.6830],
         [0.5530, 0.6602],
         [0.3941, 0.8070]],

        [[0.6608, 0.0951],
         [0.7412, 0.7291],
         [0.6156, 0.3162],
         [0.5109, 0.4989]],

        [[0.9036, 0.0930],
         [0.3454, 0.6379],
         [0.7208, 0.3233],
         [0.6800, 0.4966]]])

In [ ]:
Random.ndim


3

In [ ]:
random_img=torch.rand(size=(224,224,3))# height width and color chancel
random_img.shape,random_img.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_size= torch.rand(size=(3,4))
random_size

tensor([[0.6801, 0.0303, 0.8978, 0.3837],
        [0.2464, 0.9126, 0.9377, 0.0747],
        [0.0335, 0.9903, 0.8070, 0.7895]])

In [ ]:
## to get the zero
zero= torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## ones in the tensor
one= torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [ ]:
#using torch.range
one_to_ten=torch.arange(start=1,end=10,step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating the tensor like
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
### Tensor data Types
float_32_tensor=torch.tensor([3.,4.,4.0],
                             dtype=torch.float16,#. dtype
                             device=None, #
                             requires_grad=False)
float_32_tensor.dtype

torch.float16

# Precision os a numerical quantity is a measure of the deatils
- The main use of the dtypes for the Tensor
- take the number of space in the computer
**Note:** Tensor data types is oner of the 3 big errors youwill run pytorch and deep learning
- Tensor not right data types
- Tensor not ion correct shape
- Tensors not on the right device (device)

In [ ]:
float_16_tensor =float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 4.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 16.], dtype=torch.float16)

In [ ]:
int_32= torch.tensor([3,4,56],dtype=torch.int32)
int_32

tensor([ 3,  4, 56], dtype=torch.int32)

In [ ]:
float_16_tensor*int_32

tensor([  9.,  16., 224.], dtype=torch.float16)

In [ ]:
int_16= torch.tensor([3,4,56],dtype=torch.int16)
int_16

tensor([ 3,  4, 56], dtype=torch.int16)

In [ ]:
int_16*int_32

tensor([   9,   16, 3136], dtype=torch.int32)

### Getting information from the Tensore (Tensor attributes)
1. Tensor not right data type - to do get datatype from Tensor can use `tensor.dtype`
2. Tensor are not right Shape - to get the shape fromn the tensor can use `tensor.shape`
3. Tensor are not on right device - to get the device from a tensor can use `tensor.device`

In [ ]:
some_ran= torch.rand(size=(3,4))
print("shape",some_ran.shape)
print("dtype",some_ran.dtype)
print("device",some_ran.device)



shape torch.Size([3, 4])
dtype torch.float32
device cpu


In [ ]:
some_ran

tensor([[0.3373, 0.2898, 0.6898, 0.7479],
        [0.1496, 0.0711, 0.7412, 0.1154],
        [0.4861, 0.1723, 0.0733, 0.6449]])

# Manupulating the Tensors (Operation)
- Addition
- Multiplication
- substraction
- division
- matrix multiplication

In [ ]:
# create \a tensor
tensor = torch.tensor([10,20,30])
add =tensor+10
add

tensor([20, 30, 40])

In [ ]:
multiplication =tensor*10
multiplication

tensor([100, 200, 300])

In [ ]:
subtraction = tensor-10
subtraction

tensor([ 0, 10, 20])

In [ ]:
# using the operation
op_add = torch.add(tensor,10)
op_add

tensor([20, 30, 40])

In [ ]:
op_mul = torch.multiply(tensor,10)
op_mul

tensor([100, 200, 300])

# matrix multipication
Two Type of multipication
- element wise multipication
- matrix multipication (dot product)

In [ ]:
print(op_add)
print(add)
op_add * add

tensor([20, 30, 40])
tensor([20, 30, 40])


tensor([ 400,  900, 1600])

In [ ]:
# matmultipication
print(op_add)
print(add)
torch.matmul(op_add,add)

tensor([20, 30, 40])
tensor([20, 30, 40])


tensor(2900)

In [ ]:
# one of the common error in the deep learing :shape errors
tens_A = torch.tensor([[1,2],[3,4],[5,6]])
tens_B = torch.tensor([[3,4],[5,4],[7,6]])
tens_B=tens_B.T
#torch.matmul(tens_A,tens_B)
torch.mm(tens_A,tens_B)

tensor([[11, 13, 19],
        [25, 31, 45],
        [39, 49, 71]])

### Tensor aggregation
- Find the min,max,mean,sum

In [ ]:
# create the a tensor
x= torch.arange(0,10,1)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.min(x),torch.max(x)

(tensor(0), tensor(9))

In [ ]:
# float dtype is used for the mean
torch.mean(x)

tensor(4.5000)

In [ ]:
x.dtype

torch.int64

In [ ]:
x=x.type(torch.float32)

In [ ]:
torch.sum(x)

tensor(45.)

In [ ]:
#finding the positional min and max
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
torch.argsort(x,descending=True)

tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Reshaping, stacking, Squeezing and unsqueezing tensors
* reshaping - reshaping an input tensor to a defined shape
* view  - returing a view of the tensor of certain shape but keep the same memory as the original tensor
* stacking - combining multiple tensors on top of each other (v stack or side by side (hstack)
* squeeze - remall 1 dimention from the tensor
* unsqueeze - add 1 dimention to a target tensor
* permute - return a vieqw of the input with dimention permuted (swapped) in a ceratain way

In [ ]:
y= torch.arange(1,10)

In [ ]:
y,y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshape=y.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# change the view
z= y.view(1,9)
z[:,0]=5
z,y
## changing the z changes x they share the mamory

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# stacking
x_stacking=torch.stack([x,x,x,x],dim=-1)
x_stacking,x_stacking.shape

(tensor([[0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([10, 4]))

In [ ]:
x_squeeze= torch.squeeze(x_stacking)
x_squeeze,x_squeeze.shape

(tensor([[0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([10, 4]))

In [ ]:
x_squeeze.shape


torch.Size([10, 4])

In [ ]:
torch.squeeze(x_squeeze).shape

torch.Size([10, 4])

In [ ]:
x_permuted = torch.rand([2,4])
x_permuted

tensor([[0.2768, 0.2234, 0.5130, 0.7321],
        [0.1035, 0.6031, 0.0231, 0.1669]])

In [ ]:
x_permuted.permute(0,1)

tensor([[0.7652, 0.8116, 0.2811, 0.9563],
        [0.9711, 0.6617, 0.2229, 0.2707]])

In [ ]:
x_permuted.dim()

2

### who to use the Gpu
- The reason we want our tensors/model on the gpu is because using a Gpu resulting in faster computation

In [ ]:
# move tensor to gpu (if availble )
x= torch.tensor([1,3,5,6,8])
print(x,x.device)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 3, 5, 6, 8]) cpu
cpu


tensor([10, 20, 30])